### PR TITLE
Node v0.10.x compatibility

### PR DESCRIPTION
**Pull request by springmeyer**
All tests are passing with both:
- node v0.10.16 / OS X
- node v0.8.25 / OS X

Unblocks https://github.com/mapbox/node-tilejson/pull/7 and https://github.com/mapbox/tilelive-s3/pull/8

### CODE REVIEW

**Comment by springmeyer** [comment]
@ianshward - was it https://github.com/isaacs/node/commit/327b6e3e1de88ba1db83142d53b3a57f0d06d519 that required the `resume`?

**Comment by springmeyer** [comment]
@ianshward - are you worried about the stability of this `resume()` with node v0.8.x at all? Any reason to hold on this merge or just call the `resume` if running v0.10.x? I don't see any reason this is not safe to merge as is on my end.

**Comment by ianshward** [comment]
@springmeyer apologies for not responding earlier.  I am not totally sure there are no negative effects of calling resume on 0.8.x since the stream is already unpaused.  I saw the Knox project used this as a stop gap https://github.com/LearnBoost/knox/commit/4836dbb6d07424a5d2058aabe24cee5f8167dff2 but then eventually switched to using stream-counter https://github.com/LearnBoost/knox/commit/f040b5ff17d47f2f030e8d35399c2e89278698b6 and I'd wondered whether node-get shouldn't some similar.

**Comment by ianshward** [comment]
@springmeyer ignore what I said about stream-counter, I misunderstood what it was being used for.  It looks like Knox completely removed the data listener and now expects the implementer to handle adding it.  Looking at the Knox readme it also mentions the need to call resume in certain circumstances, like on writable stream responses.

**Comment by springmeyer** [comment]
Okay thanks @ianshward. So sounds like this could be merged then after more testing?

**Comment by yhahn** [comment]
Merged -- I will roll a breaking release version with this change.

**Pull request merged**
